version: "2"

run:
  timeout: 5m
  issues-exit-code: 1

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gocritic
    - ineffassign

formatters:
  enable:
    - gofmt
    - goimports
